### PR TITLE
Limit stylelint tasks to plugin directory

### LINKED ISSUE #256: Add support for limiting scope of grunt
Use case:
When additional plugins needs to be installed by moodle-plugin-ci because the plugin I want to run the pipeline for depends on some other plugins, I want to run grunt and all other jobs exclusively for my plugin, NOT for the dependency plugins.

Currently however, grunt for example checks all installed plugins which means also the installed plugins just needed as dependency.

There need to be a config option (or even change the default behavior) which limits the scope to the plugin itself, not the dependency plugins.

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #256

### CODE REVIEW

**Comment by stronk7** [comment]
Hi @PhMemmel ,

I've put this a little bit on hold until we discuss @ #256 . Thanks for your patience!

**Comment by stronk7** [comment]
Hi @PhMemmel ,

I've taken the liberty of amending your commit, fixing some styling details, one test that was failing and adding the information to the changelog file.

Hope that's ok for you. If you're happy, I'll be merging this once we get all checks passing.

Ciao :-)

**Comment by PhMemmel** [comment]
Feel free to add whatever is necessary! Thank you very much for taking over!

**Review by stronk7 — APPROVED** [review]

**Comment by stronk7** [comment]
Merged, let's see if we can roll this soon... thanks @PhMemmel !

**Pull request merged**
