### PR TITLE
Prepare for 3.0.5 release

### PR DESCRIPTION
**Pull request by stronk7**
Part of the release process: https://moodlehq.github.io/moodle-plugin-ci/ReleaseNewVersion.html

### CODE REVIEW

**Comment by stronk7** [comment]
(this has to be "Rebased and merged", not merged, see the release docs)

**Comment by stronk7** [comment]
(rebased to be on top of latest changes)

**Review by kabalin — APPROVED** [review]
Looks good, thanks!

**Comment by stronk7** [comment]
(Rebased and merged, thanks for the thoughtful review, lol)

**Pull request merged**
