### PR TITLE
Bump to codechecker/codenisffer 3.0

### PR DESCRIPTION
**Pull request by stronk7**
Changes in commands are important because all the old CLI machinery
in phpcs 3.0 has been removed. There were some different solutions
for this:

- start using the bin/phpcs binary (exec) and forget.
- create a custom runner/reporter like we did in local_codechecker.
- use exclusively the new phpcs 3.0 classes to get it done.

While I was really tempted to re-use the local_codechecker custom
runner / reporter, finally I went the pure phpcs classes way to
avoid creating any dependency on local_codechecker (apart from the
standard).

Unit tests have been slightly improved to better assert that all the
expected elements in the output are there.

Finally, we have had to instruct phpcs where the PHPCompatibility
standard is because, when running from PHAR, the CodeSniffer.conf
file bundled is not read and it's expected to be in real filesystem.
This was causing codechecher not to work from PHAR, so we are now
configuring it from the commands (Checker and Fixer).

### CODE REVIEW

**Comment by stronk7** [comment]
Ok, I've fixed the problem with the phpunit switches being passed to phpcs, it's know issue and there is a constant, now defined to instruct to tests to ignore extra options.

Also, I've added the `--verbose` option (extra commit, to be removed) to see which PHP version is exactly being used by CIs (travis and gha), because, apparently, the coverage-text report is being generated with both... let's see...

**Comment by stronk7** [comment]
Grrr, everything is passing... using local` bin/moodle-plugin-ci` seems to work ok too... but then I built the `moodle-plugin-ci.phar` and whenever I try to run codechecker I get this:

```
$ php moodle-plugin-ci.phar codechecker local/codechecker
 RUN  Moodle Code Checker on local_codechecker

In Runner.php line 336:
                                                             
  ERROR: Referenced sniff "PHPCompatibility" does not exist  
                                                             
  Run "phpcs --help" for usage information                   
                                                             

codechecker [-s|--standard STANDARD] [--max-warnings MAX-WARNINGS] [--] <plugin>
```

Just guessing if this has worked ever, because I see that phpcs has code to detect if it's running in phar environment and maybe that's interfering... looking... tired!

Ciao :-)

**Comment by stronk7** [comment]
Confirmed, when running from a PHAR, phpcs looks for a `CodeSniffer.conf` file in the same path the PHAR is, ignoring the bundled `CodeSniffer.conf` available @ base dir.

So I need to introduce the information in that `CodeSniffer.conf` (`installed_paths`) in a different way, when the information is not found (running as PHAR).

Will look to it later.

**Comment by stronk7** [comment]
Yay, it seems that was able to configure those `installed_paths` without needing to have them in configuration.

Now both the binary:
````
$ ../moodle-plugin-ci/bin/moodle-plugin-ci codechecker local/codechecker 
 RUN  Moodle Code Checker on local_codechecker
........EEE.EEEEEEEEEEE...W..EEEEEEEEEEEEE.................W 60 / 64 (94%)
...
FILE: /Users/stronk7/git_moodle/moodle/local/codechecker/moodle/tests/fixtures/moodle_files_moodleinternal/warning.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------
 32 | WARNING | [ ] Expected MOODLE_INTERNAL check or config.php inclusion. Multiple artifacts detected.
    |         |     (moodle.Files.MoodleInternal.MoodleInternalMultipleArtifacts)
...
...
```

And the PHAR:
````
$ ../moodle-plugin-ci/build/moodle-plugin-ci.phar codechecker local/codechecker 
 RUN  Moodle Code Checker on local_codechecker
........EEE.EEEEEEEEEEE...W..EEEEEEEEEEEEE.................W 60 / 64 (94%)
...
FILE: /Users/stronk7/git_moodle/moodle/local/codechecker/moodle/tests/fixtures/moodle_files_moodleinternal/warning.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------
 32 | WARNING | [ ] Expected MOODLE_INTERNAL check or config.php inclusion. Multiple artifacts detected.
    |         |     (moodle.Files.MoodleInternal.MoodleInternalMultipleArtifacts)
 ...
...
````

Are working perfectly!

Same for the fixer, btw:
````
$ ../moodle-plugin-ci/bin/moodle-plugin-ci phpcbf local/codechecker 
 RUN  Code Beautifier and Fixer on local_codechecker
........FFF.FFF.....F.F......F.F.F.F....F................... 60 / 64 (94%)
...
PHPCBF RESULT SUMMARY
...

$ ../moodle-plugin-ci/build/moodle-plugin-ci.phar phpcbf local/codechecker 
 RUN  Code Beautifier and Fixer on local_codechecker
........FFF.FFF.....F.F......F.F.F.F....F................... 60 / 64 (94%)
...
PHPCBF RESULT SUMMARY
...
...
````

So, if all tests pass (cross fingers), I think this can be considered.

Ciao :-)

**Review by kabalin — APPROVED** [review]
Thanks @stronk7, great work. My only concern that there is a larch snippet of the code duplicated in both command, may be this can be defined outside command classes and reused. Although this can be done later (given we need to release ASAP).

**Comment by stronk7** [comment]
> My only concern that there is a larch snippet of the code duplicated in both command, may be this can be defined outside command classes and reused

Yeah, cannot but agree... I was exploring the possibility of making one of the Commands to extend the other too, they are 99% the same, just a flag - and 1 or 2 config settings - change the behavior from checker to fixer, really.

Let's move that to new issue (just created #74), think it's better given current timing, agree.

**Pull request merged**
