### PR TITLE
deprecates integration with PHP Copy/Paste Detector (PHPCPD) library.

### PR DESCRIPTION
**Pull request by stopfstedt**
deprecation as a stepping stone towards full removal. 

i tried to be cheeky by triggering a deprecation error when the command is executed, but that didn't pan out. 
so it's all documentation, and one `@deprecated` annotation on the command itself.

refs #262 
refs #263

### CODE REVIEW

**Comment by stronk7** [comment]
Hi again, @stopfstedt.

I’ve taken the liberty of adding one extra commit on top of your changes (squashed to just 1 commit, for clarity).

Here you can see the proposed changes: https://github.com/moodlehq/moodle-plugin-ci/compare/main...stronk7:moodle-plugin-ci:deprecate_copy_paste_detector

And here you can see how it will look for anybody running the command via GitHub workflows, with annotations reminding about the deprecation all the time:

https://github.com/stronk7/moodle-plugin-ci/actions/runs/7775806197

Tell me what do you think and, if you like it, I will add the reworked commits to your branch, so anybody else in the team, can take a look to it.

Ciao 😊

**Comment by stopfstedt** [comment]
> Tell me what do you think and, if you like it, I will add the reworked commits to your branch, so anybody else in the team, can take a look to it.

This is great, please go ahead. Thanks!

**Comment by stronk7** [comment]
> This is great, please go ahead. Thanks!

To you! I've forced-updated your branch and now it contains the 2 commits described above.

Note (for the reviewer) that it's expected for this change to cause a slight decrease in PHPUnit code coverage, but that is expected and on-purpose, because we don't want the 2 warnings (Symfony and GHA) to be emitted when running tests.

Ciao :-)

**Review by paulholden — APPROVED** [review]
LGTM

**Comment by stronk7** [comment]
Thanks @paulholden , merging this now. And thanks too @stopfstedt !

**Pull request merged**
