### PR TITLE
GitHub actions for push and pull-requests

### PR DESCRIPTION
**Pull request by kabalin**
This patch contains GitHub actions for push and pull-requests to master branch.

Addressing #54 ("release" action will be in separate PR)

### CODE REVIEW

**Comment by kabalin** [comment]
Added changes to matrix (removed 3.7, added 3.11).

**Comment by stronk7** [comment]
OT, why isn't this PR being tested by GHA? maybe [putting the branch restriction to "master" for pull requests](https://github.com/moodlehq/moodle-plugin-ci/pull/55/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R7) is what kills it?

**Comment by kabalin** [comment]
> OT, why isn't this PR being tested by GHA? maybe [putting the branch restriction to "master" for pull requests](https://github.com/moodlehq/moodle-plugin-ci/pull/55/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R7) is what kills it?

@stronk7 I think this is because of `on` condition

**Comment by kabalin** [comment]
As it is stated in [community forum](https://github.community/t/github-action-workflow-is-executed-for-a-pr-from-a-forked-repo-if-the-pr-changes-the-workflow-file/16059), for security reasons, it does not seem possible to run an action workflow from PR submitted from external repository (our actions will be the ones executed for code changes in PR, not those coming in the PRs). 

Changes to GHA workflow submitted as PRs should contain a link to action run in the repo they originated (like I did in example above), so reviewer can evaluate them. Particular care should be taken if PR contains both code and GHA changes, in this case our upstream action will be run on code changes, and action workflow may remain untested.

Also, internally we can push branch to this repo and create PR from it to master, in this case action from the branch will be the one executed.

**Comment by stronk7** [comment]
Aha, well spotted, that makes sense. So only when we have this upstream... future PRs will start getting runs against it (never against the changes in GHA coming with the PRs), clever measure to prevent abuse.

**Comment by kabalin** [comment]
Renamed Self-test, there is the latest action: https://github.com/kabalin/moodle-plugin-ci/actions/runs/387470383/workflow

**Comment by stronk7** [comment]
Here we go! Great work!

**Pull request merged**
