### PR TITLE
issue #93: injectPHPUnitFilter() review

### PR DESCRIPTION
**Pull request by ewallah**
Time to move from <filters> into <coverage>?

### CODE REVIEW

**Comment by stronk7** [comment]
Hi,

maybe we should perform the change based on the branch we are running PHPUnit? Only that way we can keep 310_STABLE and older (PHPUnit <= 8.5) working with filter/whitelist and 311_STABLE and up (PHPUnit >= 9.5) with the new coverage/include.

I haven't had a chance to try it myself... but... commands seem to have access to the branch via `this->moodle->getBranch()` and, with that information we can easily keep both alternatives working.

Ciao :-)

**Comment by ewallah** [comment]
HI,

Good point, I only wanted to move things a bit forward.

But perhaps we should also consider it is time to stop removing good configurations and only inject when there is no configuration provided?

R

**Comment by kabalin** [comment]
Closing as being addressed in b1e901ac2d which just landed via #141, thanks for your effort guys!

**Comment by stronk7** [comment]
Closing this now that #141 has been merged

**Pull request closed without merging**
