### PR TITLE
Fix the commit reference of the latest local_moodlecheck plugin

### PR DESCRIPTION
**Pull request by mudrd8mz**
The travis-ci is still using the old version of the local_moodlecheck plugin. As a result, I am seeing some false failures such as "Invalid inline phpdocs tag @see found" which I am not getting when using the latest version locally.

I suspect that the commit c006b90ac2283fed1975f7039ab9cc40c75bdf0c only raised the "version". But that does not really do anything imho without setting the "reference" hash correctly.

### CODE REVIEW

**Comment by kabalin** [comment]
Hi @mudrd8mz, thanks a lot for contribution. You need to bump version at line 67, otherwise composer will not recognise changes, then run `composer update moodlehq/moodle-local_moodlecheck` to re-generate `composer.lock` and add it to commit. Also mentioning the change in changelog would be appreciated.

@stronk7 shall we make point release following this (opportunity to test release instruction also)?

**Comment by kabalin** [comment]
May be we need to bump moodlecheck following landing of https://github.com/moodlehq/moodle-local_moodlecheck/pull/56, would be useful to have it.

**Comment by mudrd8mz** [comment]
Patch amended.

**Comment by danmarsden** [comment]
ping! - any chance of getting this merged in? - I've updated some of my code to get Green tests in plugins db, but it's getting big red failures in travis-ci

**Comment by mudrd8mz** [comment]
Patch amended again to use the latest version of the `local_moodlecheck` plugin and the change mentioned in the changelog.

**Comment by stronk7** [comment]
I've added a new commit on top of @mudrd8mz one, providing:

- bump to very-latest 79fe5956f9e9be906499c01dbc59695c2412643d (merged mins ago).
- .lock file regenerated with php70 and checking the the commit there matches the above (it was not matching in original commit)

Feel free to merge this squashed, np here.

**Review by kabalin — APPROVED** [review]
This looks good to me, thanks @mudrd8mz and @stronk7. I would probably not run composer update for all dependencies for the purpose of moodle-local_codecheck upgrade, but since we are about to release this does not matter.

**Pull request merged**
