### PR TITLE
Rename TRAVIS_BUILD_DIR env variable to CI_BUILD_DIR

### PR DESCRIPTION
**Pull request by adpe**
Will solve #105

### CODE REVIEW

**Review by kabalin — CHANGES_REQUESTED** [review]
Please make sure that `TRAVIS_BUILD_DIR` is still supported along with `CI_BUILD_DIR`, so we don't break things for people who use it already in numerous places (like myself). Eventually this can be removed when some other breaking changes will be on horizon.

**Comment by adpe** [comment]
Thanks @kabalin

I was already thinking about that ;-) But maybe it's better if you would have a look on that? For sure my code proposal will not fit your expectations.

**Comment by adpe** [comment]
Here we go @kabalin

**Review by kabalin — CHANGES_REQUESTED** [review]
The code changes look good to me, thanks @adpe . Can you please squash commits into the single one.

**Pull request closed without merging**
