### PR TITLE
docs: Add file ignoring configuration example for GHA.

### PR DESCRIPTION
**Pull request by kabalin**
Rendered change: https://github.com/kabalin/moodle-plugin-ci/blob/ignore-doc/docs/IgnoringFiles.md

### CODE REVIEW

**Comment by stronk7** [comment]
Nice work, @gjb2048 & @kabalin !

With #109 now merged... can this be close or still has a point?

BTW, note that both pull requests seem to conflict about how the global travis example is defined @  `IgnoringFiles.md` (just in case we want to, also, progress this).

**Comment by gjb2048** [comment]
@stronk7 No problem.  I changed IgnoringFiles.md at the same time as @kabalin without realising it.  Entirely up to you what version you'd like.

**Comment by kabalin** [comment]
I think it worth keeping this one too (just rebased it), it updates `docs/IgnoringFiles.md` to reflect how this should be configured in GHA.

**Review by stronk7 — APPROVED** [review]
Looks ok, good job!

**Pull request merged**
