### PR TITLE
Bump sub-tools to latest releases

### PR DESCRIPTION
**Pull request by stronk7**
This needs to be merged after #141 
    
    This bumps local ci/moodlecheck/codechecker to the latest
    released / tags created last week.
    
    Also fixes a test caused by recent changes.
    
    Finally, unrelated with this, add to the CHANGELOG all the
    changes, still missing to be documented there, since last
    release of moodle-plugin-ci

### CODE REVIEW

**Comment by stronk7** [comment]
Crap, it seems that we added some PHP 7.2 isms to latest version of codechecker. Glad they have been detected here.

Ok, keeping this on halt till I fix them in codechecker and make a new release. We need to keep PHP 7.0 working, both in codechecker and here (till we decide to move up).

**Comment by stronk7** [comment]
Have made a new local_codechecker release (v3.0.4) with code downgraded to be PHP 7.0 compliant. PR updated to use that v3.0.4 version... let's see.

**Comment by stronk7** [comment]
Ok, it seems that all pieces are now in place, this should be ready now.

**Comment by stronk7** [comment]
(have rebased it on top of current master)

**Review by kabalin — APPROVED** [review]
Thanks!

**Comment by stronk7** [comment]
ty!

**Pull request merged**
