### PR TITLE
Don't publish port at selenium container

### LINKED ISSUE #147: [Docker] WARNING: Published ports are discarded when using host network mode
Hello Everyone,
today I carefully read the output of the Behat section to debug a plug-in of mine and I read about a docker warning:
```
...
Unable to find image 'selenium/standalone-chrome:3' locally
3: Pulling from selenium/standalone-chrome
...
Digest: sha256:ae50e81aa6f23e0073ac9ca43a6d182081b42a001e1c61e5dcb1e29937767d8a
Status: Downloaded newer image for selenium/standalone-chrome:3
WARNING: Published ports are discarded when using host network mode
...
```
That warning comes from:
https://github.com/moodlehq/moodle-plugin-ci/blob/78bc70629c31e243a748ab1fa56df8e2acfd8c06/src/Command/BehatCommand.php#L141

Docker docs are pretty clear: https://docs.docker.com/network/host/.
It's worth deciding not to publish the port (properly binded to IPv4 `localhost`) or not to use _host networking_.

Looking at the past history, the command has been introduced in https://github.com/moodlehq/moodle-plugin-ci/commit/04abd982b71eacd61b647ec8a764698260803c3c from https://github.com/open-lms-open-source/moodle-plugin-ci/issues/99#issuecomment-617493290, already both publishing the port and using _host networking_.

HTH,
Matteo

### PR DESCRIPTION
**Pull request by kabalin**
As we already use host networking. Fixes #147

### CODE REVIEW

**Comment by scara** [comment]
HI @kabalin,
thanks for your PR.

Wondering the reason for Travis failures: maybe that was the reason to keep both port binding and host networking.

HTH,
Matteo

**Comment by kabalin** [comment]
Hi @scara, yes, it could be a reason (I remember there was something about those params use, but can't remember what exactly).

**Comment by stronk7** [comment]
I've just relaunched the jobs. I think I've seen travis getting stuck similarly in the past, not often, but sometimes. I'm not sure if it's related with caches... or maybe some of the workers... but re-running the same jobs have "fixed" the runs magically.

Hence, trying... 🤞 . Ciao :-)

**Comment by stronk7** [comment]
Yay, they passes!

And relaunched all them again (GHA and Travis), let's see.

**Review by stronk7 — APPROVED** [review]
All ok, it seems, hence, merging, thanks!

**Pull request merged**
