### PR TITLE
Bump to current local_ci and local_moodlecheck

### PR DESCRIPTION
**Pull request by stronk7**
Not much to say, just bump to current ones to verify they pass and to have the latest fixes applied.

### CODE REVIEW

**Comment by stronk7** [comment]
My +1 to your fixes, @kabalin , thanks! It had been hours for me to understand (in fact I still don't understand it completely, heh).

**Comment by kabalin** [comment]
psalm 4.x reports too many errors (mostly related to function return type missing) and also have php7.3 as minimum requirement, thus using latest 3.x. Potentially we can have it as composer dependency (rather than fetching using curl) in future.

**Comment by kabalin** [comment]
> My +1 to your fixes, @kabalin , thanks! It had been hours for me to understand (in fact I still don't understand it completely, heh).

No problem at all 😉

**Review by kabalin — APPROVED** [review]
The version bump part looks OK to me.

**Comment by stronk7** [comment]
(self-merging, so I can continue with codechecker bump now, thanks!)

**Pull request merged**
